fileVersion: 1
id: 5ccc3974-3487-4355-a371-7a302a9e5046
name: INT_JIRA__FIELD_HISTORY_SCD_SET_VALUES
operation:
  config:
    clusterKey: false
    downstreamOption: false
    groupByAll: false
    initialize: ON_CREATE
    insertStrategy: INSERT
    lagSpecification:
      items:
        - lagPeriod: Minutes
          lagValue: 60
    orderby: false
    postSQL: ""
    preSQL: ""
    refresh_mode: AUTO
    secureoption: false
    selectDistinct: false
    testsEnabled: true
    truncateBefore: true
    warehouseName: dev_xs_wh
  database: ""
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: INT
  materializationType: dynamic table
  metadata:
    appliedNodeTests: []
    columns:
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 5a5a4f20-f70a-48b5-baee-4b16bb1ba248
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: DATE
        description: ""
        name: VALID_STARTING_ON
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3f09a7d-bf19-4c26-876c-5a10ad320d30
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: ed07ea11-e7ec-4e94-aeaf-b518a418630a
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: NUMBER(38,0)
        description: ""
        name: ISSUE_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c3cce28e-521d-4641-9c59-987ef68aba50
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 6175abc9-dc40-4aae-8883-0fce0e8442ad
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: STRING
        description: ""
        name: ISSUE_DAY_ID
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: bf293913-b3c0-4f46-a596-499cde51c573
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 67ec9f01-b75a-4064-9cdf-a4ca02b23071
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: STRING
        description: ""
        name: STATUS_ID
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: be53b761-c7ba-442c-aab6-e0c40a3df40a
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 20be67c0-e09f-43f6-af5a-d4379ada3e3f
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: NUMBER
        description: ""
        name: STATUS_ID_FIELD_PARTITION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3f09a7d-bf19-4c26-876c-5a10ad320d30
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: |-
              sum( case when "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."STATUS" is null then 0 else 1 end) over ( partition by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."ISSUE_ID" 
                          order by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."VALID_STARTING_ON" rows unbounded preceding)
      - appliedColumnTests: {}
        columnReference:
          columnCounter: d8829808-c17b-40dd-ab26-e9b15322a31c
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: STRING
        description: ""
        name: STATUS
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: be53b761-c7ba-442c-aab6-e0c40a3df40a
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: e3b9f2fd-b14a-401c-9abb-46d4637a32d6
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: NUMBER
        description: ""
        name: STATUS_FIELD_PARTITION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3f09a7d-bf19-4c26-876c-5a10ad320d30
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: |-
              sum( case when "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."STATUS" is null then 0 else 1 end) over ( partition by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."ISSUE_ID" 
                          order by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."VALID_STARTING_ON" rows unbounded preceding)
      - appliedColumnTests: {}
        columnReference:
          columnCounter: c5611a4b-66b0-4eab-9ad4-4bdc12908ac7
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: STRING
        description: ""
        name: SPRINT
        nullable: true
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: f56f77b1-a6be-4512-bdc1-86cd756118f3
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: ""
      - appliedColumnTests: {}
        columnReference:
          columnCounter: 1704e3ea-6e79-4534-b603-c0032e2c96df
          stepCounter: 5ccc3974-3487-4355-a371-7a302a9e5046
        config: {}
        dataType: NUMBER
        description: ""
        name: SPRINT_ID_FIELD_PARTITION
        nullable: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a3f09a7d-bf19-4c26-876c-5a10ad320d30
                stepCounter: 975cd647-48af-4ce7-978a-f96e658f847d
            transform: |-
              sum( case when "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."SPRINT" is null then 0 else 1 end) over ( partition by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."ISSUE_ID" 
                          order by "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"."VALID_STARTING_ON" rows unbounded preceding)
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          INT_JIRA__PIVOT_DAILY_FIELD_HISTORY: 975cd647-48af-4ce7-978a-f96e658f847d
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: INT
            nodeName: INT_JIRA__PIVOT_DAILY_FIELD_HISTORY
        join:
          joinCondition: FROM {{ ref('INT', 'INT_JIRA__PIVOT_DAILY_FIELD_HISTORY') }} "INT_JIRA__PIVOT_DAILY_FIELD_HISTORY"
        name: INT_JIRA__FIELD_HISTORY_SCD_SET_VALUES
        noLinkRefs: []
  name: INT_JIRA__FIELD_HISTORY_SCD_SET_VALUES
  overrideSQL: false
  schema: ""
  sqlType: DT113:::156
  type: sql
  version: 1
type: Node
